### ISSUE TITLE
Use of eods box for signaling chunk boundaries

### ISSUE THREAD

**Issue by jeoliva** [gpac/node-gpac-dash#9]
Hi,

While working in low latency feature for dash.js and researching why content generated with node-gpac-dash is not compatible with it, I have discovered a problem related with the use of eods boxes for signaling chunk boundaries. Neither in Chrome nor Firefox the use of eods as a top level box is allowed and so, parsing process fails and playback doesn't work. 

@cconcolato, is there any specification/proposal that points to the use of eods boxes for signaling chunk boundaries? I didn't find it in CMAF spec so I guess it might be an arbitrary decision taken by gpac. Not a problem with this (the use of eods boxes), I am just working in a fix for Chromium codebase and would like to document it appropriately. 

Thanks!

**Comment by jeanlf** [comment]
No, the eods is specific to this project - I think the simplest way for your fix would be to patch the server to avoid sending the last 8 bytes of the segment (eods box size+type)

**Comment by rbouqueau** [comment]
The appropriate thing may be to patch tis node-gpac-dash HTTP server to not return the last 8 bytes.

**Comment by jeoliva** [comment]
Makes sense. Thanks both for the quick response!

**Comment by cconcolato** [comment]
@jeoliva The option is already [there](https://github.com/gpac/node-gpac-dash/blob/master/gpac-dash.js#L17) in node-gpac-dash:
```
-no-marker-write       strip marker of the generated bitstream (default false)
```

That said, it would be good if browsers would be more robust and simply ignore boxes they don't understand.
